# Generated by Django 2.1.1 on 2018-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsraw',
            name='caption',
            field=models.CharField(help_text='Enter the artists post caption', max_length=5000),
        ),
        migrations.AlterField(
            model_name='artistsraw',
            name='display_url',
            field=models.URLField(max_length=500),
        ),
    ]
