# Generated by Django 2.1.1 on 2018-09-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20180913_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsraw',
            name='country',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='artistsraw',
            name='loc_lat',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='artistsraw',
            name='loc_long',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='artistsraw',
            name='loc_name',
            field=models.CharField(blank=True, help_text='Enter the artists post caption', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='artistsraw',
            name='rejected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artistsraw',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter the artists post caption', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artistsraw',
            name='city',
            field=models.CharField(blank=True, help_text='Enter the artists post caption', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artistsraw',
            name='display_url',
            field=models.CharField(blank=True, help_text='Enter the artists post caption', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artistsraw',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Enter the artists post caption', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artistsraw',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='artistsraw',
            name='shortcode',
            field=models.CharField(blank=True, help_text='Enter the artists post caption', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artistsraw',
            name='state',
            field=models.CharField(blank=True, help_text='Enter the artists post caption', max_length=5000, null=True),
        ),
    ]
