# Generated by Django 2.1.1 on 2018-09-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20180913_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsraw',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the artists post caption', max_length=5000, null=True),
        ),
    ]
