# Generated by Django 2.1.1 on 2018-09-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20180913_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsraw',
            name='rejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
